trigger:
  batch: true
  branches:
    include:
    - master

pr: none

pool:
  vmImage: 'ubuntu-latest'

steps:
- template: templates/app-test.yml
- task: Docker@2
  displayName: 'Build Docker image and push'
  inputs:
    containerRegistry: 'wso2choreo-control-plane-acr'
    repository: 'choreoipaas/choreo-console'
    Dockerfile: 'Dockerfile'
    buildContext: '.'
    tags: latest